/**
 * Quizo — Java & Spring Boot revision question bank
 */
const TOPICS = [
  {
    id: "java-core",
    name: "Java Core",
    icon: "☕",
    description: "Types, operators, control flow, exceptions, and language fundamentals.",
  },
  {
    id: "oop",
    name: "OOP & Classes",
    icon: "🧱",
    description: "Inheritance, polymorphism, abstraction, encapsulation, and class design.",
  },
  {
    id: "collections",
    name: "Collections & Streams",
    icon: "📦",
    description: "List, Set, Map, Concurrent collections, and Stream API.",
  },
  {
    id: "concurrency",
    name: "Concurrency",
    icon: "⚡",
    description: "Threads, executors, locks, volatile, and concurrent utilities.",
  },
  {
    id: "jvm",
    name: "JVM & Memory",
    icon: "🧠",
    description: "Memory model, GC, class loading, and performance basics.",
  },
  {
    id: "spring-core",
    name: "Spring Core",
    icon: "🌱",
    description: "IoC, DI, beans, scopes, and ApplicationContext.",
  },
  {
    id: "spring-boot",
    name: "Spring Boot",
    icon: "🚀",
    description: "Auto-config, starters, properties, actuators, and Boot conventions.",
  },
  {
    id: "spring-data",
    name: "Spring Data & JPA",
    icon: "🗄️",
    description: "Repositories, entities, transactions, and query methods.",
  },
  {
    id: "spring-web",
    name: "Spring Web & REST",
    icon: "🌐",
    description: "Controllers, request mapping, validation, and REST best practices.",
  },
  {
    id: "spring-security",
    name: "Spring Security",
    icon: "🔐",
    description: "Authentication, authorization, filters, JWT, and method security.",
  },
];

const QUESTIONS = [
  // ─── Java Core ───────────────────────────────────────────
  {
    id: "jc1",
    topic: "java-core",
    difficulty: "easy",
    question: "What is the default value of an uninitialized <code>int</code> field in a class?",
    options: ["0", "null", "undefined", "It causes a compile error"],
    answer: 0,
    explanation:
      "Instance fields of type int are automatically initialized to 0. Local variables are not initialized and must be assigned before use.",
  },
  {
    id: "jc2",
    topic: "java-core",
    difficulty: "easy",
    question: "Which keyword is used to prevent a class from being subclassed?",
    options: ["static", "final", "private", "abstract"],
    answer: 1,
    explanation: "A final class cannot be extended. Examples: String, Integer, and Math are final.",
  },
  {
    id: "jc3",
    topic: "java-core",
    difficulty: "medium",
    question: "What does <code>==</code> compare for two String objects?",
    options: [
      "Character content equality",
      "Reference (identity) equality",
      "Hash code equality",
      "Lexicographic order",
    ],
    answer: 1,
    explanation:
      "For objects, == compares references. Use equals() for content comparison. String interning can make == appear to work for literals, but equals() is correct.",
  },
  {
    id: "jc4",
    topic: "java-core",
    difficulty: "medium",
    question: "Which exception is checked (must be handled or declared)?",
    options: ["NullPointerException", "IllegalArgumentException", "IOException", "ArrayIndexOutOfBoundsException"],
    answer: 2,
    explanation:
      "IOException is a checked exception. RuntimeException and its subclasses (NPE, IAE, AIOOBE) are unchecked.",
  },
  {
    id: "jc5",
    topic: "java-core",
    difficulty: "medium",
    question: "What is the output type of <code>5 / 2</code> when both operands are int?",
    options: ["2.5 (double)", "2 (int)", "2.0 (double)", "Compile error"],
    answer: 1,
    explanation: "Integer division truncates toward zero, so 5/2 = 2. Use 5.0/2 or cast for floating-point division.",
  },
  {
    id: "jc6",
    topic: "java-core",
    difficulty: "hard",
    question: "What does the try-with-resources statement require of the resource?",
    options: [
      "It must implement Serializable",
      "It must implement AutoCloseable (or Closeable)",
      "It must be a File type",
      "It must override finalize()",
    ],
    answer: 1,
    explanation:
      "try-with-resources works with AutoCloseable (Closeable extends it). Resources are closed automatically in reverse order of declaration.",
  },
  {
    id: "jc7",
    topic: "java-core",
    difficulty: "medium",
    question: "Which is true about Java's <code>String</code> class?",
    options: [
      "Strings are mutable",
      "Strings are immutable",
      "String is a primitive type",
      "String overrides == for content equality",
    ],
    answer: 1,
    explanation:
      "String is immutable. Mutations create new objects. StringBuilder/StringBuffer are used for mutable character sequences.",
  },
  {
    id: "jc8",
    topic: "java-core",
    difficulty: "hard",
    question: "What is autoboxing?",
    options: [
      "Automatic conversion of primitives to their wrapper types",
      "Automatic garbage collection of boxed objects",
      "Casting between related classes",
      "Converting arrays to Lists",
    ],
    answer: 0,
    explanation:
      "Autoboxing converts primitives to wrappers (e.g. int → Integer). Unboxing is the reverse. Watch for NullPointerException when unboxing null.",
  },
  {
    id: "jc9",
    topic: "java-core",
    difficulty: "easy",
    question: "Which access modifier makes a member visible only within its own package (no subclasses outside)?",
    options: ["public", "protected", "private", "package-private (default)"],
    answer: 3,
    explanation:
      "Default (no modifier) is package-private. protected also allows subclass access across packages.",
  },
  {
    id: "jc10",
    topic: "java-core",
    difficulty: "medium",
    question: "What does <code>Optional</code> help avoid?",
    options: [
      "Checked exceptions",
      "NullPointerException from missing values",
      "ClassCastException",
      "OutOfMemoryError",
    ],
    answer: 1,
    explanation:
      "Optional makes absence of a value explicit and encourages safe handling via orElse, ifPresent, map, etc., reducing NPEs from null returns.",
  },

  // ─── OOP ─────────────────────────────────────────────────
  {
    id: "oop1",
    topic: "oop",
    difficulty: "easy",
    question: "Which OOP principle hides internal state and exposes controlled access?",
    options: ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
    answer: 2,
    explanation:
      "Encapsulation bundles data with methods and uses access modifiers / getters-setters to control visibility.",
  },
  {
    id: "oop2",
    topic: "oop",
    difficulty: "easy",
    question: "Can an abstract class in Java have constructors?",
    options: ["No, never", "Yes", "Only if it has no abstract methods", "Only private constructors"],
    answer: 1,
    explanation:
      "Abstract classes can have constructors, typically called by subclasses via super(). You still cannot instantiate the abstract class directly.",
  },
  {
    id: "oop3",
    topic: "oop",
    difficulty: "medium",
    question: "What is method overriding?",
    options: [
      "Same method name, different parameter lists in the same class",
      "Subclass provides a new implementation of a superclass method",
      "Hiding a static method",
      "Defining a method with the same name in a different package",
    ],
    answer: 1,
    explanation:
      "Overriding replaces a parent instance method in a subclass. Overloading is same name + different parameters in the same class.",
  },
  {
    id: "oop4",
    topic: "oop",
    difficulty: "medium",
    question: "Which is true about interfaces in modern Java (8+)?",
    options: [
      "Interfaces cannot have any methods with bodies",
      "Interfaces can have default and static methods with bodies",
      "Interfaces can have instance fields",
      "A class can implement only one interface",
    ],
    answer: 1,
    explanation:
      "Java 8+ allows default and static methods in interfaces. Fields in interfaces are public static final. Classes can implement multiple interfaces.",
  },
  {
    id: "oop5",
    topic: "oop",
    difficulty: "hard",
    question: "What is the diamond problem, and how does Java handle it for classes?",
    options: [
      "Multiple inheritance of classes is allowed with conflict resolution",
      "Java allows only single class inheritance, avoiding the diamond problem for classes",
      "Java merges conflicting methods automatically",
      "It only applies to enums",
    ],
    answer: 1,
    explanation:
      "Java forbids multiple class inheritance. Multiple interface inheritance can create diamond issues with default methods; the compiler requires the class to resolve conflicts.",
  },
  {
    id: "oop6",
    topic: "oop",
    difficulty: "medium",
    question: "What does the <code>@Override</code> annotation do?",
    options: [
      "Forces the method to be abstract",
      "Ensures a method correctly overrides a superclass/interface method at compile time",
      "Makes the method final",
      "Enables runtime polymorphism",
    ],
    answer: 1,
    explanation:
      "@Override is a compile-time check. If the method does not override anything, the compiler errors—catching typos and signature mismatches.",
  },
  {
    id: "oop7",
    topic: "oop",
    difficulty: "hard",
    question: "When should you override <code>equals()</code> and <code>hashCode()</code> together?",
    options: [
      "Never — only equals is needed",
      "Always when equals is overridden, to satisfy the equals/hashCode contract",
      "Only for enums",
      "Only when using TreeMap",
    ],
    answer: 1,
    explanation:
      "Equal objects must have equal hash codes. Breaking this contract breaks HashMap/HashSet. Prefer Objects.hash() and careful field selection.",
  },
  {
    id: "oop8",
    topic: "oop",
    difficulty: "medium",
    question: "What is composition preferred over inheritance for?",
    options: [
      "Code reuse without tight coupling to a parent hierarchy",
      "Faster method dispatch",
      "Avoiding constructors",
      "Making classes final",
    ],
    answer: 0,
    explanation:
      "Composition (has-a) is more flexible and less brittle than deep inheritance (is-a). Favor composition when reuse is about behavior, not identity.",
  },

  // ─── Collections ─────────────────────────────────────────
  {
    id: "col1",
    topic: "collections",
    difficulty: "easy",
    question: "Which collection does not allow duplicate elements?",
    options: ["ArrayList", "LinkedList", "HashSet", "Vector"],
    answer: 2,
    explanation: "Set implementations (HashSet, TreeSet, LinkedHashSet) reject duplicates based on equals/hashCode (or Comparator for TreeSet).",
  },
  {
    id: "col2",
    topic: "collections",
    difficulty: "easy",
    question: "What is the time complexity of <code>HashMap.get()</code> on average?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answer: 0,
    explanation:
      "Average-case get/put is O(1). Worst case degrades with hash collisions (historically O(n); tree bins in modern JDKs improve this to O(log n)).",
  },
  {
    id: "col3",
    topic: "collections",
    difficulty: "medium",
    question: "Which List preserves insertion order and allows fast random access?",
    options: ["LinkedList", "ArrayList", "HashSet", "PriorityQueue"],
    answer: 1,
    explanation:
      "ArrayList is array-backed: O(1) random access, amortized O(1) append. LinkedList is better for frequent middle inserts/removes with iterators.",
  },
  {
    id: "col4",
    topic: "collections",
    difficulty: "medium",
    question: "What does <code>stream().map()</code> do?",
    options: [
      "Filters elements by a predicate",
      "Transforms each element via a function",
      "Sorts the stream",
      "Collects to a Map only",
    ],
    answer: 1,
    explanation: "map applies a Function to each element, producing a stream of results. filter removes elements; collect terminates the pipeline.",
  },
  {
    id: "col5",
    topic: "collections",
    difficulty: "hard",
    question: "Why is ConcurrentHashMap preferred over Collections.synchronizedMap for high concurrency?",
    options: [
      "It is immutable",
      "It uses finer-grained locking / CAS for better throughput",
      "It allows null keys",
      "It is sorted",
    ],
    answer: 1,
    explanation:
      "ConcurrentHashMap allows concurrent reads and segmented/CAS-based updates without locking the entire map. synchronizedMap locks the whole map on every operation.",
  },
  {
    id: "col6",
    topic: "collections",
    difficulty: "medium",
    question: "What is a terminal operation in the Stream API?",
    options: [
      "map",
      "filter",
      "collect",
      "peek",
    ],
    answer: 2,
    explanation:
      "Terminal operations (collect, forEach, reduce, count, findFirst, etc.) trigger pipeline execution. Intermediate ops (map, filter) are lazy.",
  },
  {
    id: "col7",
    topic: "collections",
    difficulty: "hard",
    question: "What happens if you modify a collection while iterating with a fail-fast iterator?",
    options: [
      "Silent data corruption",
      "ConcurrentModificationException (typically)",
      "The iterator restarts",
      "The change is ignored",
    ],
    answer: 1,
    explanation:
      "ArrayList/HashMap iterators are fail-fast and throw ConcurrentModificationException on structural modification (except via iterator.remove()).",
  },
  {
    id: "col8",
    topic: "collections",
    difficulty: "medium",
    question: "Which Map implementation keeps keys sorted?",
    options: ["HashMap", "LinkedHashMap", "TreeMap", "IdentityHashMap"],
    answer: 2,
    explanation:
      "TreeMap is a Red-Black tree sorted by natural order or Comparator. LinkedHashMap preserves insertion/access order but is not sorted by key.",
  },

  // ─── Concurrency ─────────────────────────────────────────
  {
    id: "con1",
    topic: "concurrency",
    difficulty: "easy",
    question: "What does the <code>synchronized</code> keyword provide?",
    options: [
      "Faster execution",
      "Mutual exclusion (and memory visibility) on a monitor",
      "Automatic parallelization",
      "Immutable objects",
    ],
    answer: 1,
    explanation:
      "synchronized acquires a monitor lock for exclusive access and establishes happens-before for visibility between threads.",
  },
  {
    id: "con2",
    topic: "concurrency",
    difficulty: "medium",
    question: "What is the main purpose of <code>volatile</code>?",
    options: [
      "Atomic compound operations",
      "Visibility of writes across threads (and ordering for that variable)",
      "Preventing garbage collection",
      "Making methods synchronized",
    ],
    answer: 1,
    explanation:
      "volatile ensures visibility of the latest write and prevents certain reorderings. It does not make i++ atomic — use AtomicInteger for that.",
  },
  {
    id: "con3",
    topic: "concurrency",
    difficulty: "medium",
    question: "Which ExecutorService method submits a task and returns a Future?",
    options: ["execute()", "submit()", "run()", "start()"],
    answer: 1,
    explanation:
      "submit() returns Future. execute() is fire-and-forget (Runnable, no Future). start() is for Thread.",
  },
  {
    id: "con4",
    topic: "concurrency",
    difficulty: "hard",
    question: "What is a deadlock?",
    options: [
      "A thread waiting forever on I/O",
      "Two or more threads each holding a lock the other needs, waiting forever",
      "Stack overflow from recursion",
      "GC thrashing",
    ],
    answer: 1,
    explanation:
      "Deadlock requires circular wait. Mitigate with consistent lock ordering, tryLock timeouts, or fewer locks.",
  },
  {
    id: "con5",
    topic: "concurrency",
    difficulty: "hard",
    question: "What does <code>CompletableFuture</code> enable?",
    options: [
      "Only blocking sequential tasks",
      "Async composition of stages (thenApply, thenCompose, allOf, etc.)",
      "Replacing the JVM thread model",
      "Only UI animations",
    ],
    answer: 1,
    explanation:
      "CompletableFuture supports non-blocking async pipelines, combining futures, and custom executors — modern alternative to nested callbacks.",
  },
  {
    id: "con6",
    topic: "concurrency",
    difficulty: "medium",
    question: "ThreadLocal is best used for:",
    options: [
      "Sharing data between all threads",
      "Per-thread isolated state (e.g. user context, SimpleDateFormat)",
      "Global configuration",
      "Replacing synchronized always",
    ],
    answer: 1,
    explanation:
      "ThreadLocal stores values per thread. Always remove() in thread pools to avoid memory leaks (request-scoped data sticking to reused threads).",
  },

  // ─── JVM ─────────────────────────────────────────────────
  {
    id: "jvm1",
    topic: "jvm",
    difficulty: "easy",
    question: "Where are object instances stored in the JVM heap model?",
    options: ["Stack", "Heap", "Metaspace only", "Registers only"],
    answer: 1,
    explanation:
      "Objects live on the heap. Local variables and references live on the stack (per thread). Class metadata is in Metaspace (Java 8+).",
  },
  {
    id: "jvm2",
    topic: "jvm",
    difficulty: "medium",
    question: "What is the purpose of garbage collection?",
    options: [
      "Compile Java to bytecode",
      "Automatically reclaim memory from unreachable objects",
      "Optimize SQL queries",
      "Load classes from disk",
    ],
    answer: 1,
    explanation:
      "GC frees heap memory of objects no longer reachable. Different collectors (G1, ZGC, Parallel) trade throughput vs latency.",
  },
  {
    id: "jvm3",
    topic: "jvm",
    difficulty: "medium",
    question: "What is Metaspace used for?",
    options: [
      "Storing local variables",
      "Class metadata (replacing PermGen in Java 8+)",
      "Caching HTTP responses",
      "Native thread stacks only",
    ],
    answer: 1,
    explanation:
      "Metaspace holds class metadata and grows by default (native memory). OutOfMemoryError: Metaspace can occur with classloader leaks.",
  },
  {
    id: "jvm4",
    topic: "jvm",
    difficulty: "hard",
    question: "What is JIT compilation?",
    options: [
      "Compiling .java to .class at build time",
      "Runtime compilation of hot bytecode to native code",
      "AOT only compilation",
      "Interpreting SQL",
    ],
    answer: 1,
    explanation:
      "The HotSpot JIT compiles frequently executed (hot) methods to optimized native code, often outperforming pure interpretation.",
  },
  {
    id: "jvm5",
    topic: "jvm",
    difficulty: "medium",
    question: "An <code>OutOfMemoryError: Java heap space</code> usually means:",
    options: [
      "Too many open files",
      "Heap cannot allocate more objects (leaks or undersized heap)",
      "Stack is full",
      "Disk is full",
    ],
    answer: 1,
    explanation:
      "Heap OOM: increase -Xmx after analysis, or fix memory leaks. StackOverflowError is different (deep recursion / stack size).",
  },

  // ─── Spring Core ─────────────────────────────────────────
  {
    id: "sc1",
    topic: "spring-core",
    difficulty: "easy",
    question: "What does IoC stand for in Spring?",
    options: [
      "Input/Output Control",
      "Inversion of Control",
      "Internal Object Cache",
      "Interface Oriented Coding",
    ],
    answer: 1,
    explanation:
      "Inversion of Control means the framework creates and wires objects. Dependency Injection is the main IoC pattern Spring uses.",
  },
  {
    id: "sc2",
    topic: "spring-core",
    difficulty: "easy",
    question: "What is the default scope of a Spring bean?",
    options: ["prototype", "request", "singleton", "session"],
    answer: 2,
    explanation:
      "Default scope is singleton: one shared instance per Spring container. prototype creates a new instance per request for that bean.",
  },
  {
    id: "sc3",
    topic: "spring-core",
    difficulty: "medium",
    question: "Which annotation marks a class as a Spring-managed component for component scanning?",
    options: ["@Inject", "@Bean", "@Component", "@Autowired"],
    answer: 2,
    explanation:
      "@Component (and stereotypes @Service, @Repository, @Controller) enable classpath scanning. @Bean is for methods in @Configuration classes.",
  },
  {
    id: "sc4",
    topic: "spring-core",
    difficulty: "medium",
    question: "Constructor injection is preferred over field injection because:",
    options: [
      "It is the only way Spring works",
      "It makes dependencies explicit, enables immutability, and simplifies testing",
      "Field injection is deprecated and removed",
      "It is faster at runtime always",
    ],
    answer: 1,
    explanation:
      "Constructor injection documents required deps, allows final fields, and works well without Spring in unit tests. Field @Autowired hides deps and hinders testing.",
  },
  {
    id: "sc5",
    topic: "spring-core",
    difficulty: "hard",
    question: "What is a circular dependency in Spring?",
    options: [
      "A bean depending on itself via the same field only",
      "Bean A needs B and B needs A during creation",
      "Two packages importing each other",
      "Recursive @Transactional calls",
    ],
    answer: 1,
    explanation:
      "Constructor injection circular deps fail at startup. Setter/field injection may work via early references but signals a design smell—refactor often.",
  },
  {
    id: "sc6",
    topic: "spring-core",
    difficulty: "medium",
    question: "What does <code>@Configuration</code> indicate?",
    options: [
      "A REST controller",
      "A class that defines @Bean methods for the application context",
      "A database config file only",
      "A properties file loader",
    ],
    answer: 1,
    explanation:
      "@Configuration classes are processed so @Bean methods produce singleton-aware beans (full mode uses CGLIB proxies).",
  },
  {
    id: "sc7",
    topic: "spring-core",
    difficulty: "hard",
    question: "What is the ApplicationContext?",
    options: [
      "Only a property file reader",
      "The Spring IoC container interface providing bean factory, events, i18n, etc.",
      "A servlet filter",
      "The JVM classloader",
    ],
    answer: 1,
    explanation:
      "ApplicationContext extends BeanFactory and adds enterprise features: events, internationalization, resource loading, and AOP integration.",
  },
  {
    id: "sc8",
    topic: "spring-core",
    difficulty: "medium",
    question: "What does <code>@Primary</code> do when multiple beans of the same type exist?",
    options: [
      "Deletes other beans",
      "Marks the preferred bean for autowiring by type",
      "Makes the bean prototype-scoped",
      "Enables lazy init",
    ],
    answer: 1,
    explanation:
      "@Primary selects the default candidate. Alternatively use @Qualifier with a bean name for explicit selection.",
  },

  // ─── Spring Boot ─────────────────────────────────────────
  {
    id: "sb1",
    topic: "spring-boot",
    difficulty: "easy",
    question: "What does <code>@SpringBootApplication</code> combine?",
    options: [
      "@Controller + @Service + @Repository",
      "@Configuration + @EnableAutoConfiguration + @ComponentScan",
      "@RestController + @RequestMapping",
      "@Entity + @Table",
    ],
    answer: 1,
    explanation:
      "@SpringBootApplication is a convenience annotation composing configuration, auto-config, and component scanning from the main class package.",
  },
  {
    id: "sb2",
    topic: "spring-boot",
    difficulty: "easy",
    question: "What is a Spring Boot 'starter'?",
    options: [
      "A main method template",
      "A dependency descriptor that pulls a curated set of libraries",
      "A database migration tool",
      "A UI component library",
    ],
    answer: 1,
    explanation:
      "Starters (e.g. spring-boot-starter-web) aggregate compatible dependencies so you don't manage versions manually (with the BOM).",
  },
  {
    id: "sb3",
    topic: "spring-boot",
    difficulty: "medium",
    question: "Where does Spring Boot look for configuration by default?",
    options: [
      "Only system environment variables",
      "application.properties / application.yml (and profiles)",
      "Only XML files in WEB-INF",
      "Only hard-coded defaults",
    ],
    answer: 1,
    explanation:
      "Boot loads application.properties/yml from classpath root, config/, etc., plus profile-specific files like application-dev.yml.",
  },
  {
    id: "sb4",
    topic: "spring-boot",
    difficulty: "medium",
    question: "How do you activate a Spring profile named <code>prod</code>?",
    options: [
      "spring.profiles.active=prod",
      "spring.active.profile=prod",
      "@Profile(\"prod\") on main only",
      "profile=prod in pom.xml only",
    ],
    answer: 0,
    explanation:
      "Set spring.profiles.active=prod via properties, env (SPRING_PROFILES_ACTIVE), or CLI --spring.profiles.active=prod.",
  },
  {
    id: "sb5",
    topic: "spring-boot",
    difficulty: "hard",
    question: "What does auto-configuration do?",
    options: [
      "Generates REST controllers from entities always",
      "Conditionally creates beans based on classpath and properties",
      "Disables all manual @Bean methods",
      "Replaces application.properties",
    ],
    answer: 1,
    explanation:
      "Auto-config classes use @ConditionalOnClass, @ConditionalOnMissingBean, etc. You can exclude or override by defining your own beans.",
  },
  {
    id: "sb6",
    topic: "spring-boot",
    difficulty: "medium",
    question: "What is Spring Boot Actuator used for?",
    options: [
      "UI theming",
      "Production-ready endpoints (health, metrics, info, etc.)",
      "ORM mapping",
      "Message queue brokers",
    ],
    answer: 1,
    explanation:
      "Actuator exposes ops endpoints like /actuator/health and metrics. Secure them in production—don't expose everything publicly.",
  },
  {
    id: "sb7",
    topic: "spring-boot",
    difficulty: "hard",
    question: "What is the role of <code>spring-boot-starter-parent</code>?",
    options: [
      "It embeds Tomcat only",
      "It provides dependency management (versions) and plugin defaults for Maven",
      "It is required for Gradle only",
      "It replaces application.yml",
    ],
    answer: 1,
    explanation:
      "The parent POM manages versions via dependency management and configures plugins. Gradle uses the dependency management plugin / BOM similarly.",
  },
  {
    id: "sb8",
    topic: "spring-boot",
    difficulty: "medium",
    question: "How can you externalize a server port?",
    options: [
      "server.port=8081 in application properties",
      "Only by recompiling",
      "port.server=8081",
      "tomcat.port only",
    ],
    answer: 0,
    explanation:
      "server.port is the standard property. Override via env SERVER_PORT or CLI --server.port=8081 without rebuilding.",
  },

  // ─── Spring Data & JPA ───────────────────────────────────
  {
    id: "sd1",
    topic: "spring-data",
    difficulty: "easy",
    question: "What annotation marks a JPA entity class?",
    options: ["@Table", "@Entity", "@Repository", "@Document"],
    answer: 1,
    explanation:
      "@Entity marks a JPA persistent class. @Table customizes the table name; @Repository is for Spring DAO beans; @Document is typically MongoDB.",
  },
  {
    id: "sd2",
    topic: "spring-data",
    difficulty: "easy",
    question: "Spring Data JPA repository interfaces typically extend:",
    options: [
      "JdbcTemplate",
      "JpaRepository or CrudRepository",
      "EntityManager directly as interface",
      "HashMap",
    ],
    answer: 1,
    explanation:
      "JpaRepository provides CRUD, paging, and flushing helpers. Spring generates implementations at runtime.",
  },
  {
    id: "sd3",
    topic: "spring-data",
    difficulty: "medium",
    question: "What does <code>findByEmail(String email)</code> in a repository do?",
    options: [
      "Requires a custom implementation class always",
      "Is derived from the method name into a query",
      "Only works with native SQL",
      "Is ignored by Spring Data",
    ],
    answer: 1,
    explanation:
      "Query derivation parses method names into predicates. For complex queries use @Query or Specifications.",
  },
  {
    id: "sd4",
    topic: "spring-data",
    difficulty: "medium",
    question: "What does <code>@Transactional</code> do on a service method?",
    options: [
      "Makes the method async",
      "Demarcates a database transaction (commit/rollback)",
      "Caches the return value",
      "Validates JSON only",
    ],
    answer: 1,
    explanation:
      "Spring starts a transaction, commits on success, rolls back on runtime exceptions by default. Self-invocation bypasses the proxy.",
  },
  {
    id: "sd5",
    topic: "spring-data",
    difficulty: "hard",
    question: "What is the N+1 select problem?",
    options: [
      "Using N databases plus one cache",
      "One query loads parents, then one query per child relation (N extra queries)",
      "N threads plus one lock",
      "Pagination off-by-one",
    ],
    answer: 1,
    explanation:
      "Lazy associations trigger extra queries in a loop. Fix with join fetch, @EntityGraph, or batch fetching.",
  },
  {
    id: "sd6",
    topic: "spring-data",
    difficulty: "hard",
    question: "LazyInitializationException typically occurs when:",
    options: [
      "You use eager fetching",
      "You access a lazy association outside an active persistence context/session",
      "The database is read-only",
      "You use JdbcTemplate",
    ],
    answer: 1,
    explanation:
      "Common after the transaction closes (e.g. in the view layer). Keep loading in the service transaction or use DTOs/fetch joins.",
  },
  {
    id: "sd7",
    topic: "spring-data",
    difficulty: "medium",
    question: "What is the purpose of <code>@GeneratedValue</code>?",
    options: [
      "Generate random test data",
      "Configure how primary key values are generated",
      "Auto-create REST endpoints",
      "Generate equals/hashCode",
    ],
    answer: 1,
    explanation:
      "@GeneratedValue works with @Id strategies like IDENTITY, SEQUENCE, or UUID generators depending on the database and provider.",
  },
  {
    id: "sd8",
    topic: "spring-data",
    difficulty: "medium",
    question: "Dirty checking in JPA means:",
    options: [
      "Validating SQL injection",
      "Automatically detecting field changes on managed entities and issuing UPDATEs",
      "Scanning for unused beans",
      "Cleaning temporary tables",
    ],
    answer: 1,
    explanation:
      "Managed entities are tracked; at flush/commit, JPA compares state and generates updates. Detached entities need merge or explicit updates.",
  },

  // ─── Spring Web ──────────────────────────────────────────
  {
    id: "sw1",
    topic: "spring-web",
    difficulty: "easy",
    question: "What does <code>@RestController</code> combine?",
    options: [
      "@Controller + @ResponseBody",
      "@Service + @Component",
      "@Entity + @Table",
      "@RequestMapping + @GetMapping only",
    ],
    answer: 0,
    explanation:
      "@RestController is @Controller + @ResponseBody on every method—return values are written to the HTTP body (usually JSON).",
  },
  {
    id: "sw2",
    topic: "spring-web",
    difficulty: "easy",
    question: "Which annotation maps HTTP GET requests?",
    options: ["@PostMapping", "@GetMapping", "@PutMapping", "@PatchMapping"],
    answer: 1,
    explanation: "@GetMapping is shorthand for @RequestMapping(method = GET). Use POST/PUT/PATCH/DELETE variants for other verbs.",
  },
  {
    id: "sw3",
    topic: "spring-web",
    difficulty: "medium",
    question: "How do you bind a path variable like <code>/users/{id}</code>?",
    options: [
      "@RequestParam Long id",
      "@PathVariable Long id",
      "@RequestBody Long id",
      "@CookieValue Long id",
    ],
    answer: 1,
    explanation:
      "@PathVariable binds URI template variables. @RequestParam binds query string params (?id=). @RequestBody binds the body.",
  },
  {
    id: "sw4",
    topic: "spring-web",
    difficulty: "medium",
    question: "What does <code>@Valid</code> on a @RequestBody trigger?",
    options: [
      "Authentication",
      "Bean Validation (JSR-380) on the payload",
      "SQL validation",
      "CORS checks",
    ],
    answer: 1,
    explanation:
      "With a validator on the classpath, @Valid/@Validated runs constraints (@NotNull, @Size, etc.). Failures typically become 400 via MethodArgumentNotValidException.",
  },
  {
    id: "sw5",
    topic: "spring-web",
    difficulty: "hard",
    question: "What is the role of <code>@ControllerAdvice</code>?",
    options: [
      "Only logging requests",
      "Global exception handling and cross-cutting controller concerns",
      "Defining security filters",
      "Creating datasources",
    ],
    answer: 1,
    explanation:
      "@ControllerAdvice + @ExceptionHandler centralize error responses. Can also add global @ModelAttribute and @InitBinder logic.",
  },
  {
    id: "sw6",
    topic: "spring-web",
    difficulty: "medium",
    question: "Idempotent HTTP methods can safely be retried. Which is typically idempotent?",
    options: ["POST", "GET", "CONNECT", "None of them"],
    answer: 1,
    explanation:
      "GET, PUT, and DELETE are defined as idempotent. POST is not (multiple calls may create multiple resources).",
  },
  {
    id: "sw7",
    topic: "spring-web",
    difficulty: "hard",
    question: "What does <code>ResponseEntity&lt;T&gt;</code> allow you to control?",
    options: [
      "Only the body type erasure",
      "HTTP status, headers, and body together",
      "Only content negotiation",
      "Database isolation level",
    ],
    answer: 1,
    explanation:
      "ResponseEntity lets you return e.g. 201 Created with Location header, or 404 with empty body, full control over the response.",
  },
  {
    id: "sw8",
    topic: "spring-web",
    difficulty: "medium",
    question: "Content negotiation in Spring MVC typically selects:",
    options: [
      "Which database to use",
      "Response media type (JSON/XML) based on Accept header / configuration",
      "Which thread pool to use",
      "SSL certificate",
    ],
    answer: 1,
    explanation:
      "HttpMessageConverters serialize/deserialize based on Content-Type and Accept. Jackson handles JSON by default in Boot web apps.",
  },

  // ─── Spring Security ─────────────────────────────────────
  {
    id: "ss1",
    topic: "spring-security",
    difficulty: "easy",
    question: "Authentication vs Authorization:",
    options: [
      "They are the same",
      "Authentication verifies identity; authorization checks permissions",
      "Authorization logs you in; authentication checks roles",
      "Both only apply to OAuth",
    ],
    answer: 1,
    explanation:
      "Authentication: who are you? Authorization: what are you allowed to do? Spring Security handles both via filters and voters/expressions.",
  },
  {
    id: "ss2",
    topic: "spring-security",
    difficulty: "easy",
    question: "Passwords should be stored as:",
    options: [
      "Plain text",
      "Reversible encryption only",
      "One-way hashed (e.g. BCrypt) with salt",
      "Base64 encoding",
    ],
    answer: 2,
    explanation:
      "Use PasswordEncoder (BCryptPasswordEncoder, Argon2, etc.). Base64 is encoding, not security. Never store reversible passwords if avoidable.",
  },
  {
    id: "ss3",
    topic: "spring-security",
    difficulty: "medium",
    question: "In the filter chain, CSRF protection mainly defends against:",
    options: [
      "SQL injection",
      "Cross-Site Request Forgery (unwanted state-changing requests from another site)",
      "XSS only",
      "DDoS",
    ],
    answer: 1,
    explanation:
      "CSRF tokens ensure state-changing requests originate from your app. Stateless JWT APIs often disable CSRF carefully with other mitigations.",
  },
  {
    id: "ss4",
    topic: "spring-security",
    difficulty: "medium",
    question: "What does <code>SecurityFilterChain</code> bean configure (Spring Security 5.7+/6)?",
    options: [
      "Only CORS",
      "HTTP security: authorize requests, login, CSRF, session, etc.",
      "Only JPA auditing",
      "Only actuator endpoints",
    ],
    answer: 1,
    explanation:
      "The SecurityFilterChain DSL replaces the old WebSecurityConfigurerAdapter for configuring HTTP security rules.",
  },
  {
    id: "ss5",
    topic: "spring-security",
    difficulty: "hard",
    question: "What is a JWT commonly used for in APIs?",
    options: [
      "Storing large binary files",
      "Stateless authentication tokens carrying claims",
      "Database connection pooling",
      "Replacing HTTPS",
    ],
    answer: 1,
    explanation:
      "JWTs (signed) carry claims (sub, roles, exp). Servers validate signature without server-side session. Watch token size, revocation, and secret management.",
  },
  {
    id: "ss6",
    topic: "spring-security",
    difficulty: "medium",
    question: "Method security with <code>@PreAuthorize(\"hasRole('ADMIN')\")</code> requires:",
    options: [
      "Nothing special",
      "@EnableMethodSecurity (or legacy @EnableGlobalMethodSecurity)",
      "Only CSRF disabled",
      "Actuator on classpath",
    ],
    answer: 1,
    explanation:
      "Enable method security so AOP proxies enforce annotations. hasRole adds ROLE_ prefix by default (hasRole('ADMIN') → ROLE_ADMIN).",
  },
  {
    id: "ss7",
    topic: "spring-security",
    difficulty: "hard",
    question: "What does the SecurityContext hold?",
    options: [
      "Datasource credentials only",
      "Authentication details for the current thread/request",
      "All HTTP headers permanently",
      "Open JPA sessions",
    ],
    answer: 1,
    explanation:
      "SecurityContext (via SecurityContextHolder) stores Authentication. Propagated per request; careful with async threads (need mode/strategy).",
  },
  {
    id: "ss8",
    topic: "spring-security",
    difficulty: "medium",
    question: "CORS is primarily about:",
    options: [
      "Encrypting cookies",
      "Browser cross-origin request policies for frontends on different origins",
      "SQL column access",
      "JVM memory limits",
    ],
    answer: 1,
    explanation:
      "Browsers enforce Same-Origin Policy. CORS headers (Access-Control-Allow-Origin, etc.) allow controlled cross-origin API access from SPAs.",
  },

  // ─── Java Core (extra) ───────────────────────────────────
  {
    id: "jc11",
    topic: "java-core",
    difficulty: "easy",
    question: "Which keyword is used to inherit from a class in Java?",
    options: ["implements", "extends", "inherits", "super"],
    answer: 1,
    explanation: "extends is for class inheritance. implements is for interfaces. super refers to the parent.",
  },
  {
    id: "jc12",
    topic: "java-core",
    difficulty: "easy",
    question: "What is the size of a Java <code>int</code>?",
    options: ["16 bits", "32 bits", "64 bits", "Platform-dependent"],
    answer: 1,
    explanation: "Java primitive sizes are fixed: int is always 32-bit signed, long is 64-bit, regardless of OS/CPU.",
  },
  {
    id: "jc13",
    topic: "java-core",
    difficulty: "medium",
    question: "What does <code>String.intern()</code> do?",
    options: [
      "Converts string to lowercase",
      "Returns a canonical representation from the string pool",
      "Encrypts the string",
      "Splits the string",
    ],
    answer: 1,
    explanation:
      "intern() returns the pooled equal string so identical contents can share one instance. Overuse can pressure the pool/Metaspace.",
  },
  {
    id: "jc14",
    topic: "java-core",
    difficulty: "medium",
    question: "Which is true about <code>switch</code> on Strings (Java 7+)?",
    options: [
      "Not allowed",
      "Allowed; uses equals under the hood",
      "Only works for string length &lt; 10",
      "Requires hashCode override on String",
    ],
    answer: 1,
    explanation: "Switch on String is supported and compares with equals. Cases must be constant strings.",
  },
  {
    id: "jc15",
    topic: "java-core",
    difficulty: "hard",
    question: "What is the difference between <code>checked</code> and <code>unchecked</code> exceptions?",
    options: [
      "Checked must be declared or handled; unchecked need not",
      "Unchecked must be declared; checked need not",
      "Checked only occur at compile time",
      "There is no difference at runtime",
    ],
    answer: 0,
    explanation:
      "Checked exceptions (Exception except RuntimeException) must be caught or declared. Unchecked (RuntimeException/Error) do not.",
  },
  {
    id: "jc16",
    topic: "java-core",
    difficulty: "medium",
    question: "What does the <code>transient</code> keyword mean on a field?",
    options: [
      "Field is thread-local",
      "Field is skipped during default Java serialization",
      "Field cannot be final",
      "Field is volatile",
    ],
    answer: 1,
    explanation: "transient fields are not written by default ObjectOutputStream serialization. Useful for secrets or derived cache fields.",
  },
  {
    id: "jc17",
    topic: "java-core",
    difficulty: "easy",
    question: "Which method is the entry point of a standard Java application?",
    options: [
      "public void start(String[] args)",
      "public static void main(String[] args)",
      "public static int run()",
      "public void main()",
    ],
    answer: 1,
    explanation: "The JVM looks for public static void main(String[] args) (or varargs String...).",
  },
  {
    id: "jc18",
    topic: "java-core",
    difficulty: "hard",
    question: "What is type erasure in Java generics?",
    options: [
      "Generic type parameters are removed at compile time; runtime sees raw types",
      "Generics are reified and available via reflection always",
      "All generic types become Object at compile time only, not runtime",
      "Erasure only applies to arrays",
    ],
    answer: 0,
    explanation:
      "Java generics use type erasure: List&lt;String&gt; becomes List at runtime. That is why you cannot do new T() or check instanceof List&lt;String&gt;.",
  },
  {
    id: "jc19",
    topic: "java-core",
    difficulty: "medium",
    question: "Which statement about enums is true?",
    options: [
      "Enums cannot have methods",
      "Enum constants are public static final instances",
      "Enums can extend other classes",
      "Enums are mutable by default",
    ],
    answer: 1,
    explanation:
      "Each enum constant is a public static final instance of the enum type. Enums can have fields/methods but cannot extend a class (they implicitly extend Enum).",
  },
  {
    id: "jc20",
    topic: "java-core",
    difficulty: "hard",
    question: "What does <code>var</code> (Java 10+) do for local variables?",
    options: [
      "Makes the variable dynamically typed at runtime",
      "Infers the static type at compile time from the initializer",
      "Allows changing type later",
      "Works for fields without initializer",
    ],
    answer: 1,
    explanation:
      "var is compile-time type inference. The variable still has a fixed static type; it is not dynamic typing like JavaScript.",
  },

  // ─── OOP (extra) ─────────────────────────────────────────
  {
    id: "oop9",
    topic: "oop",
    difficulty: "easy",
    question: "Polymorphism allows:",
    options: [
      "A parent reference to call subclass-overridden methods at runtime",
      "Multiple inheritance of classes",
      "Private fields to be public",
      "Skipping constructors",
    ],
    answer: 0,
    explanation: "Runtime polymorphism (dynamic dispatch) invokes the overridden method based on the actual object type.",
  },
  {
    id: "oop10",
    topic: "oop",
    difficulty: "medium",
    question: "Can a static method be overridden?",
    options: [
      "Yes, exactly like instance methods",
      "No — static methods are hidden, not overridden",
      "Only if marked final",
      "Only in interfaces",
    ],
    answer: 1,
    explanation:
      "Static methods bind to the class (compile-time). A subclass can declare the same signature (hiding), but it is not polymorphic override.",
  },
  {
    id: "oop11",
    topic: "oop",
    difficulty: "medium",
    question: "What is the Liskov Substitution Principle (LSP)?",
    options: [
      "Prefer composition",
      "Subtypes must be usable wherever their base type is expected without breaking behavior",
      "One class, one reason to change",
      "Depend on abstractions",
    ],
    answer: 1,
    explanation: "LSP: objects of a superclass should be replaceable with subclasses without altering correctness of the program.",
  },
  {
    id: "oop12",
    topic: "oop",
    difficulty: "hard",
    question: "When is a shallow copy insufficient?",
    options: [
      "When the object has only primitives",
      "When nested mutable objects must be independent copies",
      "When using enums",
      "When the class is final",
    ],
    answer: 1,
    explanation:
      "Shallow copy duplicates references. Nested mutable state is shared. Deep copy clones nested structures when independence is required.",
  },
  {
    id: "oop13",
    topic: "oop",
    difficulty: "medium",
    question: "What does <code>super()</code> do in a constructor?",
    options: [
      "Calls a static method",
      "Invokes a superclass constructor",
      "Creates a new subclass",
      "Finalizes the object",
    ],
    answer: 1,
    explanation: "super() or super(args) must be the first statement when used; it chains construction to the parent class.",
  },
  {
    id: "oop14",
    topic: "oop",
    difficulty: "easy",
    question: "An interface with a single abstract method is often called:",
    options: ["Marker interface", "Functional interface", "Abstract class", "Mixin"],
    answer: 1,
    explanation: "Functional interfaces (e.g. Runnable, Comparator, Function) can be targeted by lambdas. Annotate with @FunctionalInterface.",
  },
  {
    id: "oop15",
    topic: "oop",
    difficulty: "hard",
    question: "Why can implementing <code>Cloneable</code> be problematic?",
    options: [
      "It is too fast",
      "clone() is awkward, shallow by default, and often better replaced by copy constructors/factories",
      "It requires Spring",
      "It only works on primitives",
    ],
    answer: 1,
    explanation:
      "Cloneable is a marker with a protected Object.clone() design many consider flawed. Prefer copy constructors or builders.",
  },

  // ─── Collections (extra) ─────────────────────────────────
  {
    id: "col9",
    topic: "collections",
    difficulty: "easy",
    question: "Which method adds an element to the end of an ArrayList?",
    options: ["put()", "add()", "append()", "insert()"],
    answer: 1,
    explanation: "List.add(E) appends. add(index, E) inserts at a position. Map uses put.",
  },
  {
    id: "col10",
    topic: "collections",
    difficulty: "medium",
    question: "What does <code>Collectors.toMap</code> risk if keys collide?",
    options: [
      "Silent overwrite always",
      "IllegalStateException unless a merge function is provided",
      "NullPointerException always",
      "It never allows duplicates",
    ],
    answer: 1,
    explanation:
      "Without a merge function, duplicate keys throw IllegalStateException. Provide (a,b) -&gt; b or similar to resolve.",
  },
  {
    id: "col11",
    topic: "collections",
    difficulty: "medium",
    question: "Difference between <code>flatMap</code> and <code>map</code> on streams?",
    options: [
      "flatMap is only for parallel streams",
      "flatMap maps each element to a stream and flattens into one stream",
      "map always returns List",
      "There is no difference",
    ],
    answer: 1,
    explanation: "map: 1→1 transform. flatMap: 1→0..n, then flatten (e.g. list of lists to single stream).",
  },
  {
    id: "col12",
    topic: "collections",
    difficulty: "hard",
    question: "Why might you use <code>CopyOnWriteArrayList</code>?",
    options: [
      "Frequent writes, rare reads",
      "Mostly reads, infrequent writes (snapshot iteration without locking readers)",
      "Sorted unique elements",
      "Primitive int storage",
    ],
    answer: 1,
    explanation:
      "COWAL copies the array on each mutation. Great for listener lists; poor for write-heavy workloads.",
  },
  {
    id: "col13",
    topic: "collections",
    difficulty: "easy",
    question: "Which collection is a FIFO queue by default with LinkedList?",
    options: ["Stack only", "Queue (offer/poll)", "Map", "Set"],
    answer: 1,
    explanation: "LinkedList implements Queue/Deque. offer adds to tail, poll removes from head — FIFO.",
  },
  {
    id: "col14",
    topic: "collections",
    difficulty: "hard",
    question: "What does <code>Stream.parallel()</code> do?",
    options: [
      "Always faster results",
      "Enables multi-threaded pipeline execution (with overhead; not always faster)",
      "Makes the stream infinite",
      "Sorts automatically",
    ],
    answer: 1,
    explanation:
      "Parallel streams use the common ForkJoinPool. Beneficial for large CPU-bound work; can hurt for small/IO-bound or shared mutable state.",
  },
  {
    id: "col15",
    topic: "collections",
    difficulty: "medium",
    question: "Immutable list factory in modern Java:",
    options: [
      "new ArrayList&lt;&gt;() is immutable",
      "List.of(...)",
      "Arrays.asList is fully immutable and resizable",
      "Collections.emptySet() returns a List",
    ],
    answer: 1,
    explanation:
      "List.of / Set.of / Map.of create unmodifiable collections. Arrays.asList is fixed-size but settable; not fully immutable.",
  },

  // ─── Concurrency (extra) ─────────────────────────────────
  {
    id: "con7",
    topic: "concurrency",
    difficulty: "easy",
    question: "How do you start a new Thread with a Runnable?",
    options: [
      "runnable.run() only",
      "new Thread(runnable).start()",
      "Thread.execute(runnable)",
      "Executor.start(runnable) only option",
    ],
    answer: 1,
    explanation: "start() schedules a new thread. Calling run() directly executes on the current thread.",
  },
  {
    id: "con8",
    topic: "concurrency",
    difficulty: "medium",
    question: "What is a race condition?",
    options: [
      "Two threads racing to finish first harmlessly",
      "Incorrect behavior due to unsynchronized concurrent access to shared state",
      "Only GC pauses",
      "Network latency",
    ],
    answer: 1,
    explanation: "Race conditions occur when outcome depends on interleaving of unsynchronized accesses. Fix with locks, atomics, or immutability.",
  },
  {
    id: "con9",
    topic: "concurrency",
    difficulty: "medium",
    question: "What does <code>CountDownLatch</code> do?",
    options: [
      "Caches results",
      "Lets threads wait until a count reaches zero",
      "Replaces synchronized forever",
      "Sorts tasks",
    ],
    answer: 1,
    explanation: "One-shot barrier: await() blocks until countDown() has been called enough times. Cannot be reset (use CyclicBarrier for reuse).",
  },
  {
    id: "con10",
    topic: "concurrency",
    difficulty: "hard",
    question: "What is the happens-before relationship?",
    options: [
      "A GUI layout rule",
      "A JMM guarantee that memory writes are visible in a defined order across threads",
      "SQL transaction isolation",
      "Class loading order only",
    ],
    answer: 1,
    explanation:
      "Happens-before (via synchronized, volatile, joining threads, etc.) ensures visibility and ordering between actions in different threads.",
  },
  {
    id: "con11",
    topic: "concurrency",
    difficulty: "hard",
    question: "ReentrantLock advantage over synchronized?",
    options: [
      "It is always faster",
      "Supports tryLock, timed lock, fairness, multiple conditions",
      "No need to unlock",
      "Works without try/finally",
    ],
    answer: 1,
    explanation:
      "Explicit locks offer tryLock(), lockInterruptibly(), fair ordering, and multiple Condition objects. Always unlock in finally.",
  },
  {
    id: "con12",
    topic: "concurrency",
    difficulty: "medium",
    question: "AtomicInteger's <code>incrementAndGet()</code> is:",
    options: [
      "Not thread-safe",
      "A lock-free atomic update (CAS under the hood)",
      "Same as i++ on int field",
      "Deprecated",
    ],
    answer: 1,
    explanation: "Atomic classes use CAS for lock-free updates. Plain i++ on a shared int is not atomic.",
  },

  // ─── JVM (extra) ─────────────────────────────────────────
  {
    id: "jvm6",
    topic: "jvm",
    difficulty: "easy",
    question: "What does the JVM execute?",
    options: [".java source files", "Bytecode (.class)", "Only machine code from day one", "SQL"],
    answer: 1,
    explanation: "javac produces bytecode; the JVM interprets/JITs that bytecode on any platform with a JVM.",
  },
  {
    id: "jvm7",
    topic: "jvm",
    difficulty: "medium",
    question: "What is a memory leak in Java (practical sense)?",
    options: [
      "Impossible because of GC",
      "Unintentionally retaining reachable references so GC cannot free memory",
      "Only native malloc bugs",
      "Too many local variables",
    ],
    answer: 1,
    explanation:
      "GC frees unreachable objects. Listeners, caches, static collections, and ThreadLocals can pin objects and cause effective leaks.",
  },
  {
    id: "jvm8",
    topic: "jvm",
    difficulty: "medium",
    question: "Young generation vs Old generation:",
    options: [
      "Young holds long-lived objects only",
      "Most new objects start in young gen; survivors may promote to old gen",
      "Old gen is only for strings",
      "No generational heap in HotSpot",
    ],
    answer: 1,
    explanation: "Generational hypothesis: most objects die young. Minor GC collects eden/survivors; full/old collections are costlier.",
  },
  {
    id: "jvm9",
    topic: "jvm",
    difficulty: "hard",
    question: "What is escape analysis used for?",
    options: [
      "Security sandboxing only",
      "Optimizations like stack allocation / scalar replacement when objects don't escape a method",
      "Detecting SQL injection",
      "Loading native libraries",
    ],
    answer: 1,
    explanation:
      "If the JIT proves an object doesn't escape, it may eliminate heap allocation (scalar replacement), reducing GC pressure.",
  },
  {
    id: "jvm10",
    topic: "jvm",
    difficulty: "medium",
    question: "ClassLoader parent-delegation model means:",
    options: [
      "Child always loads first",
      "A classloader asks its parent before loading a class itself",
      "No hierarchy exists",
      "Only one classloader in the JVM",
    ],
    answer: 1,
    explanation:
      "Standard delegation: bootstrap → platform → app. Helps consistency and security. Custom loaders can break this carefully.",
  },

  // ─── Spring Core (extra) ─────────────────────────────────
  {
    id: "sc9",
    topic: "spring-core",
    difficulty: "easy",
    question: "Stereotype for the persistence/DAO layer?",
    options: ["@Controller", "@Service", "@Repository", "@RestController"],
    answer: 2,
    explanation: "@Repository marks DAOs and enables persistence exception translation to Spring's DataAccessException hierarchy.",
  },
  {
    id: "sc10",
    topic: "spring-core",
    difficulty: "medium",
    question: "What does <code>@Lazy</code> do on a bean?",
    options: [
      "Disables the bean",
      "Defers initialization until first use",
      "Makes it prototype always",
      "Removes it from the context",
    ],
    answer: 1,
    explanation: "Lazy beans are not created at startup (unless needed for other eager beans). Useful for costly optional dependencies.",
  },
  {
    id: "sc11",
    topic: "spring-core",
    difficulty: "medium",
    question: "What is a Spring AOP proxy used for?",
    options: [
      "HTTP compression only",
      "Applying cross-cutting advice (transactions, security, logging) around bean methods",
      "Replacing the JVM",
      "Serializing beans",
    ],
    answer: 1,
    explanation:
      "Spring wraps beans in JDK or CGLIB proxies so advice runs around join points. Self-invocation bypasses the proxy.",
  },
  {
    id: "sc12",
    topic: "spring-core",
    difficulty: "hard",
    question: "When does Spring use CGLIB vs JDK dynamic proxies?",
    options: [
      "Always JDK",
      "JDK if the bean implements interfaces (historically); CGLIB for class-based proxies",
      "Always CGLIB only for final classes",
      "Never proxies",
    ],
    answer: 1,
    explanation:
      "JDK proxies require interfaces. Class-based proxies use CGLIB/ByteBuddy. Spring Boot often defaults to class proxies. Final classes/methods limit proxying.",
  },
  {
    id: "sc13",
    topic: "spring-core",
    difficulty: "medium",
    question: "What does <code>@Value(\"${app.name}\")</code> do?",
    options: [
      "Hardcodes app.name",
      "Injects a property value from the Environment",
      "Creates a new bean named app.name",
      "Validates JSON",
    ],
    answer: 1,
    explanation: "@Value resolves placeholders from properties/YAML/env. Prefer @ConfigurationProperties for groups of settings.",
  },
  {
    id: "sc14",
    topic: "spring-core",
    difficulty: "hard",
    question: "Bean post-processors are used to:",
    options: [
      "Only destroy beans",
      "Customize bean instances during init (e.g. @Autowired processing)",
      "Replace ApplicationContext",
      "Compile Java code",
    ],
    answer: 1,
    explanation:
      "BeanPostProcessor hooks run before/after init. Framework features like annotation injection are implemented this way.",
  },
  {
    id: "sc15",
    topic: "spring-core",
    difficulty: "easy",
    question: "Which annotation injects a dependency?",
    options: ["@Override", "@Autowired", "@SuppressWarnings", "@Deprecated"],
    answer: 1,
    explanation: "@Autowired (or constructor injection without annotation in recent Spring) wires collaborators from the context.",
  },

  // ─── Spring Boot (extra) ─────────────────────────────────
  {
    id: "sb9",
    topic: "spring-boot",
    difficulty: "easy",
    question: "Default embedded server for spring-boot-starter-web?",
    options: ["Jetty", "Undertow", "Tomcat", "Netty only"],
    answer: 2,
    explanation: "starter-web pulls Tomcat by default. You can exclude Tomcat and use Jetty or Undertow starters instead.",
  },
  {
    id: "sb10",
    topic: "spring-boot",
    difficulty: "medium",
    question: "How do you disable a specific auto-configuration?",
    options: [
      "Delete Spring jars",
      "@SpringBootApplication(exclude = {SomeAutoConfiguration.class})",
      "Only via XML",
      "It cannot be disabled",
    ],
    answer: 1,
    explanation:
      "exclude / excludeName on @SpringBootApplication or spring.autoconfigure.exclude property disables auto-config classes.",
  },
  {
    id: "sb11",
    topic: "spring-boot",
    difficulty: "medium",
    question: "What is application-dev.yml used for?",
    options: [
      "Production only",
      "Properties active when the 'dev' profile is enabled",
      "Replacing pom.xml",
      "Docker only",
    ],
    answer: 1,
    explanation: "Profile-specific files application-{profile}.yml load when that profile is active, layered over defaults.",
  },
  {
    id: "sb12",
    topic: "spring-boot",
    difficulty: "hard",
    question: "What does the Spring Boot DevTools module provide?",
    options: [
      "Production clustering",
      "Automatic restarts, LiveReload, and dev-friendly defaults",
      "Replacement for JPA",
      "Mandatory security",
    ],
    answer: 1,
    explanation:
      "DevTools speeds local development with restart classloader and optional browser LiveReload. Not for production.",
  },
  {
    id: "sb13",
    topic: "spring-boot",
    difficulty: "medium",
    question: "Command to run a Boot app as a fat jar?",
    options: [
      "java -jar myapp.jar",
      "javac myapp.jar",
      "npm start",
      "python myapp.jar",
    ],
    answer: 0,
    explanation: "The repackaged executable jar embeds dependencies and a launcher. Run with java -jar.",
  },
  {
    id: "sb14",
    topic: "spring-boot",
    difficulty: "hard",
    question: "What is the purpose of <code>@ConfigurationProperties</code>?",
    options: [
      "Map a prefix of properties to a typed bean",
      "Only load XML",
      "Define REST paths",
      "Enable JPA auditing",
    ],
    answer: 0,
    explanation:
      "Binds relaxed properties (e.g. app.mail.host) to fields with validation and IDE metadata support. Prefer over many @Value fields.",
  },
  {
    id: "sb15",
    topic: "spring-boot",
    difficulty: "easy",
    question: "spring.datasource.url configures:",
    options: [
      "The main class",
      "JDBC connection URL for the DataSource",
      "Actuator base path only",
      "Server SSL only",
    ],
    answer: 1,
    explanation: "Boot auto-configures a DataSource from spring.datasource.* properties when a driver is on the classpath.",
  },

  // ─── Spring Data (extra) ─────────────────────────────────
  {
    id: "sd9",
    topic: "spring-data",
    difficulty: "easy",
    question: "What annotation marks the primary key field of an entity?",
    options: ["@Primary", "@Id", "@Key", "@Column"],
    answer: 1,
    explanation: "@Id marks the primary key. Often combined with @GeneratedValue for DB-generated keys.",
  },
  {
    id: "sd10",
    topic: "spring-data",
    difficulty: "medium",
    question: "What does <code>Optional&lt;User&gt; findById</code> returning empty mean?",
    options: [
      "Database is down",
      "No entity with that id",
      "Transaction rolled back",
      "Lazy proxy failure",
    ],
    answer: 1,
    explanation: "Empty Optional means not found. Prefer Optional over null for finders.",
  },
  {
    id: "sd11",
    topic: "spring-data",
    difficulty: "medium",
    question: "CascadeType.ALL on a relationship means:",
    options: [
      "Ignore the child",
      "Propagate all persistence operations from parent to children",
      "Only DELETE cascades",
      "Eager fetch always",
    ],
    answer: 1,
    explanation:
      "Cascade.ALL includes PERSIST, MERGE, REMOVE, etc. Use carefully — cascading remove can delete more than intended.",
  },
  {
    id: "sd12",
    topic: "spring-data",
    difficulty: "hard",
    question: "What is the persistence context?",
    options: [
      "Only the database connection pool",
      "First-level cache of managed entities for a unit of work (EntityManager/Session)",
      "Second-level cache only",
      "HTTP session",
    ],
    answer: 1,
    explanation:
      "The persistence context tracks managed entities, enables dirty checking, and ensures identity scope within the context.",
  },
  {
    id: "sd13",
    topic: "spring-data",
    difficulty: "medium",
    question: "Pagination in Spring Data typically uses:",
    options: [
      "Only native SQL LIMIT in controllers",
      "Pageable / Page&lt;T&gt; on repository methods",
      "Thread.sleep",
      "ArrayList.subList only",
    ],
    answer: 1,
    explanation: "Pass PageRequest.of(page, size) as Pageable; repositories return Page or Slice with metadata.",
  },
  {
    id: "sd14",
    topic: "spring-data",
    difficulty: "hard",
    question: "Optimistic locking with JPA commonly uses:",
    options: [
      "@Version field",
      "Thread.sleep between reads",
      "Only synchronized methods",
      "Base64 encoding IDs",
    ],
    answer: 0,
    explanation:
      "@Version increments on update; conflicting updates throw OptimisticLockException. Pessimistic locking uses DB locks.",
  },
  {
    id: "sd15",
    topic: "spring-data",
    difficulty: "easy",
    question: "Which annotation runs a custom JPQL query on a repository method?",
    options: ["@Select", "@Query", "@Sql", "@Command"],
    answer: 1,
    explanation: "@Query defines JPQL or native SQL for a repository method when derivation is not enough.",
  },

  // ─── Spring Web (extra) ──────────────────────────────────
  {
    id: "sw9",
    topic: "spring-web",
    difficulty: "easy",
    question: "HTTP status 404 means:",
    options: ["OK", "Created", "Not Found", "Server Error"],
    answer: 2,
    explanation: "404 Not Found — resource does not exist. 200 OK, 201 Created, 500 Internal Server Error.",
  },
  {
    id: "sw10",
    topic: "spring-web",
    difficulty: "medium",
    question: "What does <code>@RequestBody</code> do?",
    options: [
      "Reads a cookie",
      "Deserializes the HTTP request body into a Java object",
      "Binds a path segment",
      "Sets response status only",
    ],
    answer: 1,
    explanation: "Typically JSON → object via HttpMessageConverter (Jackson). Pair with @Valid for validation.",
  },
  {
    id: "sw11",
    topic: "spring-web",
    difficulty: "medium",
    question: "Difference between <code>@Controller</code> and <code>@RestController</code>?",
    options: [
      "None",
      "RestController methods write to the response body by default; Controller often returns view names",
      "Controller cannot use @GetMapping",
      "RestController cannot return JSON",
    ],
    answer: 1,
    explanation:
      "@RestController = @Controller + @ResponseBody. Classic MVC controllers return logical view names for templates.",
  },
  {
    id: "sw12",
    topic: "spring-web",
    difficulty: "hard",
    question: "What is content type <code>application/json</code> used for?",
    options: [
      "HTML pages only",
      "JSON payloads in REST APIs",
      "Multipart file uploads only",
      "Server-sent binary images only",
    ],
    answer: 1,
    explanation: "JSON APIs use application/json for request/response bodies. Multipart is multipart/form-data.",
  },
  {
    id: "sw13",
    topic: "spring-web",
    difficulty: "medium",
    question: "Which annotation reads a query parameter <code>?page=1</code>?",
    options: ["@PathVariable", "@RequestParam", "@RequestHeader", "@MatrixVariable"],
    answer: 1,
    explanation: "@RequestParam binds query parameters. @PathVariable binds URI path templates.",
  },
  {
    id: "sw14",
    topic: "spring-web",
    difficulty: "hard",
    question: "What does <code>@CrossOrigin</code> enable?",
    options: [
      "SQL cross joins",
      "CORS for browser cross-origin calls to the annotated controller/method",
      "Multi-module Maven builds",
      "Cross-thread transactions",
    ],
    answer: 1,
    explanation: "@CrossOrigin adds CORS mappings. Prefer global CORS config for consistent API policy.",
  },
  {
    id: "sw15",
    topic: "spring-web",
    difficulty: "easy",
    question: "PUT is typically used to:",
    options: [
      "Partially update only one field always",
      "Create or fully replace a resource at a known URI",
      "Delete a resource",
      "Only fetch data",
    ],
    answer: 1,
    explanation: "PUT is idempotent full replace/create at URI. PATCH is for partial updates. DELETE removes. GET fetches.",
  },

  // ─── Spring Security (extra) ─────────────────────────────
  {
    id: "ss9",
    topic: "spring-security",
    difficulty: "easy",
    question: "What is a role in Spring Security often prefixed with?",
    options: ["USER_", "ROLE_", "AUTH_", "PERM_"],
    answer: 1,
    explanation: "By default hasRole('ADMIN') looks for authority ROLE_ADMIN. hasAuthority can match exact strings.",
  },
  {
    id: "ss10",
    topic: "spring-security",
    difficulty: "medium",
    question: "formLogin() configures:",
    options: [
      "OAuth2 only",
      "Username/password form-based authentication",
      "Only JWT",
      "Database migrations",
    ],
    answer: 1,
    explanation: "formLogin sets up the login page, success/failure handlers, and related filter processing for session-based auth.",
  },
  {
    id: "ss11",
    topic: "spring-security",
    difficulty: "medium",
    question: "httpBasic() enables:",
    options: [
      "Digest only",
      "HTTP Basic Authentication (Authorization: Basic ...)",
      "mTLS only",
      "API key in query string only",
    ],
    answer: 1,
    explanation: "Basic auth sends base64(user:pass). Prefer HTTPS. Common for simple APIs/tools; JWT/OAuth for SPAs often better.",
  },
  {
    id: "ss12",
    topic: "spring-security",
    difficulty: "hard",
    question: "What is a SecurityFilterChain ordered for?",
    options: [
      "JPA entity scanning",
      "Matching different request patterns with different security rules",
      "Sorting beans alphabetically",
      "Only logging",
    ],
    answer: 1,
    explanation:
      "Multiple SecurityFilterChain beans with @Order and securityMatcher let you secure /api/** differently from actuator or public routes.",
  },
  {
    id: "ss13",
    topic: "spring-security",
    difficulty: "hard",
    question: "SessionCreationPolicy.STATELESS is common when:",
    options: [
      "Using server sessions for every click",
      "Building token-based (e.g. JWT) APIs without HttpSession",
      "Only MVC form apps",
      "Disabling security entirely",
    ],
    answer: 1,
    explanation:
      "STATELESS avoids creating HTTP sessions; each request authenticates via token/header. Fits REST + JWT designs.",
  },
  {
    id: "ss14",
    topic: "spring-security",
    difficulty: "medium",
    question: "UserDetailsService is responsible for:",
    options: [
      "Rendering Thymeleaf",
      "Loading user data for authentication by username",
      "Opening JDBC connections only",
      "Generating JWT signatures only",
    ],
    answer: 1,
    explanation: "loadUserByUsername returns UserDetails (username, password hash, authorities) for the AuthenticationProvider.",
  },
  {
    id: "ss15",
    topic: "spring-security",
    difficulty: "easy",
    question: "Which endpoint is often used for logout in form apps?",
    options: ["/login", "/logout", "/error", "/actuator"],
    answer: 1,
    explanation: "Spring Security's logout filter typically handles POST /logout (configurable) and invalidates the session.",
  },

  // ─── Cross-cutting / practical ───────────────────────────
  {
    id: "jc21",
    topic: "java-core",
    difficulty: "medium",
    question: "What does <code>finally</code> guarantee (barring JVM halt)?",
    options: [
      "The catch block always runs",
      "The finally block runs after try/catch whether or not an exception occurred",
      "Exceptions are swallowed",
      "The method returns null",
    ],
    answer: 1,
    explanation: "finally is for cleanup. It runs on normal and exceptional paths, unless the JVM exits or the thread is killed unrecoverably.",
  },
  {
    id: "jc22",
    topic: "java-core",
    difficulty: "hard",
    question: "Records (Java 16+) are best for:",
    options: [
      "Mutable entities with complex behavior",
      "Immutable data carriers with generated equals/hashCode/toString",
      "Replacing all classes",
      "GUI components",
    ],
    answer: 1,
    explanation: "Records are transparent immutable carriers. Great for DTOs; not a full replacement for rich domain entities.",
  },
  {
    id: "sb16",
    topic: "spring-boot",
    difficulty: "medium",
    question: "What does <code>@Scheduled</code> require to work?",
    options: [
      "Nothing",
      "@EnableScheduling and a scheduled method (cron/fixedRate/etc.)",
      "Only Actuator",
      "JPA only",
    ],
    answer: 1,
    explanation: "Enable scheduling on a config/app class, then annotate methods with @Scheduled. Runs on a task scheduler thread pool.",
  },
  {
    id: "sc16",
    topic: "spring-core",
    difficulty: "medium",
    question: "Prototype-scoped bean injected into a singleton:",
    options: [
      "Gets a new prototype on every singleton method call automatically",
      "Is injected once at singleton creation (unless ObjectFactory/Provider used)",
      "Is illegal",
      "Becomes request-scoped",
    ],
    answer: 1,
    explanation:
      "Classic gotcha: singleton holds one prototype instance. Use Provider&lt;T&gt;, ObjectFactory, or lookup method for fresh instances.",
  },
  {
    id: "sd16",
    topic: "spring-data",
    difficulty: "medium",
    question: "What is Flyway/Liquibase typically used for with Spring Boot?",
    options: [
      "Frontend bundling",
      "Database schema migrations versioned with the app",
      "JWT signing",
      "Load balancing",
    ],
    answer: 1,
    explanation: "Migration tools apply ordered SQL/changesets at startup so schema evolves safely across environments.",
  },
  {
    id: "sw16",
    topic: "spring-web",
    difficulty: "hard",
    question: "Why return DTOs instead of JPA entities from REST controllers?",
    options: [
      "Entities cannot be serialized ever",
      "Avoid lazy-load issues, over-fetching, and leaking internal model/security fields",
      "DTOs are required by the JVM",
      "Entities are slower always",
    ],
    answer: 1,
    explanation:
      "DTOs decouple API contract from persistence, prevent LazyInitializationException, and control exposed fields.",
  },
  {
    id: "ss16",
    topic: "spring-security",
    difficulty: "hard",
    question: "OAuth2 Resource Server in Spring Security is used to:",
    options: [
      "Host an authorization server only",
      "Validate access tokens (e.g. JWT) on protected API requests",
      "Replace all databases",
      "Compile TypeScript",
    ],
    answer: 1,
    explanation:
      "A resource server validates bearer tokens and builds Authentication. Authorization server issues tokens (separate concern).",
  },
  {
    id: "con13",
    topic: "concurrency",
    difficulty: "medium",
    question: "Virtual threads (Project Loom / Java 21) are designed to:",
    options: [
      "Replace the garbage collector",
      "Make high-throughput concurrent blocking code cheaper with lightweight threads",
      "Eliminate all race conditions",
      "Only work with Spring 1.x",
    ],
    answer: 1,
    explanation:
      "Virtual threads are cheap to create/block, improving scalability for I/O-bound server apps. You still need correct synchronization for shared mutable state.",
  },
  {
    id: "jvm11",
    topic: "jvm",
    difficulty: "easy",
    question: "What tool inspects a heap dump for memory issues?",
    options: ["javac", "jmap/jcmd + VisualVM/Eclipse MAT", "npm audit", "ping"],
    answer: 1,
    explanation: "Capture heap dumps (jmap, jcmd, -XX:+HeapDumpOnOutOfMemoryError) and analyze with VisualVM, MAT, YourKit, etc.",
  },
  {
    id: "col16",
    topic: "collections",
    difficulty: "medium",
    question: "What does <code>Optional.orElseThrow()</code> do when empty?",
    options: [
      "Returns null",
      "Throws NoSuchElementException (or supplied exception)",
      "Returns Optional.empty()",
      "Blocks forever",
    ],
    answer: 1,
    explanation: "orElseThrow fails fast when value is missing — good for required data after a lookup.",
  },
  {
    id: "oop16",
    topic: "oop",
    difficulty: "medium",
    question: "Sealed classes (Java 17+) allow you to:",
    options: [
      "Encrypt class files",
      "Restrict which types may extend/implement a type",
      "Make all methods final automatically",
      "Disable reflection",
    ],
    answer: 1,
    explanation:
      "sealed hierarchies list permitted subclasses, enabling exhaustive switch/pattern matching and tighter domain models.",
  },
  {
    id: "sb17",
    topic: "spring-boot",
    difficulty: "hard",
    question: "spring.jpa.hibernate.ddl-auto=validate means:",
    options: [
      "Drop and recreate schema always",
      "Validate mapping against DB schema; do not modify schema",
      "Create schema if missing only",
      "Ignore the database",
    ],
    answer: 1,
    explanation:
      "validate checks entities vs schema. Prefer migrations (Flyway) in prod; avoid create-drop in production.",
  },
  {
    id: "sc17",
    topic: "spring-core",
    difficulty: "hard",
    question: "What is the Spring Environment abstraction?",
    options: [
      "Only OS environment variables",
      "Unified API over property sources (files, env, CLI, system props)",
      "The JVM heap",
      "A Docker network",
    ],
    answer: 1,
    explanation:
      "Environment aggregates PropertySources with precedence rules so @Value and binders resolve consistently.",
  },
  {
    id: "sw17",
    topic: "spring-web",
    difficulty: "medium",
    question: "Which status code is most appropriate for successful creation of a resource?",
    options: ["200 with no body only", "201 Created", "204 only", "302 Found"],
    answer: 1,
    explanation: "201 Created indicates a new resource; often include Location header. 204 is no content success.",
  },
  {
    id: "ss17",
    topic: "spring-security",
    difficulty: "medium",
    question: "passwordEncoder.encode(raw) should be used when:",
    options: [
      "Logging passwords",
      "Storing a new or changed password",
      "Comparing in plain text",
      "Sending password to the client",
    ],
    answer: 1,
    explanation: "Encode on registration/password change. On login, use matches(raw, encoded) — never re-encode and compare strings directly if salts differ.",
  },
];
